### ISSUE TITLE
add Windows CI testing

### ISSUE THREAD

**Issue by mschilli87** [BIMSBbioinfo/ciRcus#36]
This is already prepared in the `wintest` branch (see f8c52e2420d068cf961a60ae7b2f0f5480906a25).

---
Unfortunately [all the tests fail](https://ci.appveyor.com/project/mschilli87/circus/build/1.0.1#L432) as of now.
I downloaded the [failure artifact](https://ci.appveyor.com/api/buildjobs/kskj6ffcxklc0084/artifacts/failure.zip) and checked the logs.
Turns out to be the infamous [R 3.3.3.vs. Bioconductor 'could not find symbol "recursive" in environment of the generic function' issue](https://support.bioconductor.org/p/93347/#93373).

---
As the solution requires re-building packages *from source* and I have no idea how to do that in Windows (let alone in appvayor) nor the intention to figure it out, I'll leave this open and the `wintest` branch unmerged until this crazy situation is resolved upstream.

**Comment by mschilli87** [comment]
I started [testing different environment](https://ci.appveyor.com/project/mschilli87/circus/build/1.0.2).
So let's see how this works out.

**Comment by mschilli87** [comment]
@retaj: Can you comment on [this warning](https://ci.appveyor.com/project/mschilli87/circus/build/1.0.2/job/b00lr06tp7uxbl4i#L350)?
Looks like on Windows the build fails for R 3.2.5, too. 

---
As I have *(literally) zero* experience with R on Windows, maybe you find some time to help me troubleshoot/understand what's going wrong there?

**Comment by mschilli87** [comment]
@retaj bump :wink:

**Comment by retaj** [comment]
I ran R CMD check on windows 10 with R 3.3.2, and it returned no errors/warnings. Could you make Appveyor check the dev branch again before we go into details?

**Comment by mschilli87** [comment]
[done...](https://ci.appveyor.com/project/mschilli87/circus/build/1.0.4)

**Comment by retaj** [comment]
"replacing previous import 'S4Vectors::Position' by 'ggplot2::Position' when loading 'ciRcus"

Think this is not worth our time (on top of the time I wasted already). Current versions of these packages are not clashing (which is why both Travis CI and my manual builds on Win10/R 3.3.2 are fine), and both packages are very difficult to use with importFrom without breaking everything up. 

If it is possible to tell appveyor not to use the prebuilt packages, we can give it another shot, if not, I would just wait for this issue to resolve itself :)

**Comment by mschilli87** [comment]
Allright, I might give it a shot over easter.
Otherwise, I'll keep rebasing this branch on top ov `dev` until it works. :wink:

**Comment by mschilli87** [comment]
closing in favour of https://github.com/BIMSBbioinfo/ciRcus/pull/43
